language: julia

os:
- linux

julia:
- 1.0

branches:
  only:
  - glacier

notifications:
  email: false

env:
  global:
    - BINARYBUILDER_AUTOMATIC_APPLE=true

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder"'

script:
  - julia castles/glacier/BinaryBuilder_macOS.jl
