language: cpp
dist: trusty # use gcc 4.8 on linux
os:
    - windows

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always

script:
    - castles/glacier/windows-travis.sh
