name: Explore Github Actions

on:
  push:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Run a simple command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
                bash -c '
                echo -e Hello, secret: [${REPO_ACCESS_TOKEN}]
                echo $PWD, $(pwd)
                echo -----------------
                export
                '
